name: built_stream_generator
description: A new flutter package project.
version: 1.0.0
author: Dat Thanh Vo <datvt9312@gmail.com>
homepage: https://github.com/datvt9312/blocs/built_stream_generator

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  built_collection: '>=2.0.0 <5.0.0'
  built_stream:
    path: ../built_stream
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
