name: example
description: A project used to demo 
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_stream:
    path: ../built_stream/

dev_dependencies:
  build_runner: 1.0.0
  flutter_test:
    sdk: flutter
  built_stream_generator:
    path: ../built_stream_generator

