name: built_stream
description: Keep track of all your TODOs.
version: 1.0.0
author: Dat Thanh Vo <datvt9312@gmail.com>
homepage: https://github.com/datvt9312/blocs/built_stream_generator

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.3.4